version: '3.9'

x-defaults:
  - yugabyte_image: &yb-image ${YB_IMAGE:-yugabytedb/yugabyte:2.15.3.0-b231}
  - configs: &common
      networks:
        - tlr-network
      extra_hosts:
        - "host.docker.internal:host-gateway"

services:
  rev-proxy:
    <<: *common
    build: ./rev-proxy
    ports:
      - "8080:80"

  frontend:
    <<: *common
    build: ./tlr-ui
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./tlr-ui/:/app
      - /app/node_modules

  api:
    <<: *common
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=los-angeles
    ports:
      - "8000:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app

  api-washington-dc:
    <<: *common
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=washington-dc
    ports:
      - "8001:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app

  api-sao-paulo:
    <<: *common
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=sao-paulo
    ports:
      - "8002:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app

  api-mumbai:
    <<: *common
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=mumbai
    ports:
      - "8003:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app

  api-london:
    <<: *common
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=london
    ports:
      - "8004:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app

  api-sydney:
    <<: *common
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=sydney
    ports:
      - "8005:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app

  yb-master-0:
    <<: *common
    image: *yb-image
    container_name: yb-master-0
    hostname: yb-master-0
    command: &master-command bash -c "
              rm -rf /tmp/.yb* ;
              exec /home/yugabyte/bin/yb-master --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
              --fs_data_dirs=/home/yugabyte/data
              --rpc_bind_addresses=$$HOSTNAME:7100
              --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100
              --replication_factor=3
              --rpc_connection_timeout_ms=15000
              "
    ports:
      - "7001:7000"

  yb-tserver-0:
    <<: *common
    image: *yb-image
    container_name: yb-tserver-0
    hostname: yb-tserver-0
    volumes:
      - ./products_service/:/app
    command: &tserver-command bash -c "
              rm -rf /tmp/.yb* ;
              exec /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
              --placement_cloud=cloud
              --placement_region=region
              --placement_zone=zone
              --enable_ysql=true
              --fs_data_dirs=/home/yugabyte/data
              --rpc_bind_addresses=$$HOSTNAME:9100
              --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100
              --ysql_num_shards_per_tserver=2
              --rpc_connection_timeout_ms=15000
              "
    ports:
      - "9000:9000"
      - "5433:5433"
    depends_on:
      - yb-master-2

  yb-master-1:
    <<: *common
    image: *yb-image
    container_name: yb-master-1
    hostname: yb-master-1
    command: *master-command
    ports:
      - "7002:7000"
    depends_on:
      - yb-master-0

  yb-tserver-1:
    <<: *common
    image: *yb-image
    container_name: yb-tserver-1
    hostname: yb-tserver-1
    command: *tserver-command
    ports:
      - "9001:9000"
      - "5434:5433"
    depends_on:
      - yb-master-2

  yb-master-2:
    <<: *common
    image: *yb-image
    container_name: yb-master-2
    hostname: yb-master-2
    command: *master-command
    ports:
      - "7003:7000"
    depends_on:
      - yb-master-1

  yb-tserver-2:
    <<: *common
    image: *yb-image
    container_name: yb-tserver-2
    hostname: yb-tserver-2
    command: *tserver-command
    ports:
      - "9002:9000"
      - "5435:5433"
    depends_on:
      - yb-master-2

networks:
  tlr-network:
    name: tlr-network

