# stage 1
FROM node:16.15.1-alpine as build
COPY . /app
WORKDIR /app
COPY package.json/ ./
COPY package-lock.json ./
COPY ./ ./
RUN npm install
CMD npm run build

# stage 2
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
